apiVersion: apps/v1 
kind: Deployment
metadata:
  name: java-webdeployment2
spec:
  selector:
    matchLabels:
      app: java-webapp
  
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
      - name: java-webapp
        image: tejasrik/test:latest
        ports:
        - containerPort: 8080

---		
apiVersion: v1
kind: Service
metadata:
  name: my-webservice2
  labels:
    app: java-webapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080 
      nodePort: 30025
      
  selector:
    app: java-webapp
